pcm.besaudio {
	type plug
	slave.pcm {
		type besaudio
	}
}

pcm.besbt {
	type plug
	slave.pcm {
		type besbt
	}
}

pcm.besnuttx {
	@args [ DEVICE ]
	@args.DEVICE {
		type string
		default "/dev/pcm0"
	}
	type besnuttx
	device $DEVICE
	hint {
		show {
			@func refer
			name defaults.namehint.basic
		}
		description "Bes Audio"
	}
}

ctl.besnuttx {
	@args [ DEVICE ]
	@args.DEVICE {
		type string
		default "/dev/pcm0"
	}
	type besnuttx
	device $DEVICE
}

pcm.!default { type besnuttx }  
